nav:
  Home: /
  About: /about/
  Writing: /archives/
  Projects: http://github.com/kolov

projects_url: http://github.com/kolov

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: https://github.com/kolov
        twitter: https://twitter.com/kolov
        linkedin: https://www.linkedin.com/in/kolov
    show_all_posts: false
    post_count: 5
    highlight: monokai

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: blog-o1hmdueuuw
    google_analytics: UA-104680605-1 # enter the tracking ID for your Google Analytics

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
